interface InsightsPanelProps {
  type: 'developer' | 'team';
  id: string;
  data: unknown;
}

export function InsightsPanel({ type, id, data }: InsightsPanelProps) {
  const isEmpty =
    data === null || data === undefined || (typeof data === 'object' && Object.keys(data as object).length === 0);

  if (isEmpty) {
    return (
      <div className="rounded-xl border border-gray-200 bg-white p-8 text-center">
        <p className="text-sm text-gray-500">
          No {type} insights available for&nbsp;<strong>{id}</strong> yet.
        </p>
        <p className="mt-1 text-xs text-gray-400">
          Insights are generated by the Aggregator service after reviews complete.
        </p>
      </div>
    );
  }

  return (
    <div className="rounded-xl border border-gray-200 bg-white p-6">
      <pre className="overflow-auto rounded-md bg-gray-50 p-4 text-sm text-gray-800">
        {JSON.stringify(data, null, 2)}
      </pre>
    </div>
  );
}
